version:  '3'

services:
  api:
    build: .
    image: botucaflix
    restart: always
    ports:
      -3001:3001
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: botucaflixdb
      DB_HOST: db
    depends_on:
      - db
    command: dev
    volumes:
      - .:/app

  db:
    image: mysql:8.0.32
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 33061:3306
    volumes:
     - ./db_data:/var/lib/mysql