version:  '3'

services:
  api:
    build: .
    image: botucaflix
    restart: always
    ports:
      - 3001:3001
    environment:
      DB_USER: ${ENV}_DB_USER
      DB_PASSWORD: ${ENV}_DB_PASSWORD
      DB_NAME: ${ENV}_DB_NAME
      DB_HOST: ${ENV}_DB_HOST
    depends_on:
      - db
    command: dev
    volumes:
      - .:/app

  db:
    image: mysql:8.0.32
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3306
    volumes:
     - ./db_data:/var/lib/mysql